version: "2"
networks:
  backend:
    driver: bridge
services:
  webserver:
    image: php:7.4.3-apache
    ports:
      - "8181:80"
    volumes:
      - ./quizzy-p/codecanyon-27941288-quizzy-online-examination-platform:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

